"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import type { Activity, InspectedFile, PilotRun, RunError, RunEvent } from "@/lib/pilot-types";

const examples = [
  { label: "clsx #100", url: "https://github.com/lukeed/clsx/issues/100" },
  { label: "google/uuid #97", url: "https://github.com/google/uuid/issues/97" },
  { label: "clsx #112", url: "https://github.com/lukeed/clsx/issues/112" },
];

const hostedPreview = process.env.NEXT_PUBLIC_CODEX_PILOT_LIVE_RUNS === "false";

const sample: PilotRun = {
  issue: { number: 123, title: "Dark mode resets after page refresh", repository: "acme/astro-ui", url: "https://github.com/acme/astro-ui/issues/123" },
  repository: { branch: "main", language: "TypeScript", public: true, url: "https://github.com/acme/astro-ui" },
  source: "sample", status: "completed", summary: "Theme state is recreated from the default after a refresh. The patch restores the saved selection before applying it.",
  stages: [{ id: "understanding", label: "Understanding issue", status: "completed", elapsedMs: 1200 }, { id: "exploring", label: "Exploring repository", status: "completed", elapsedMs: 3800 }, { id: "planning", label: "Planning", status: "completed", elapsedMs: 4700 }, { id: "writing", label: "Generating patch", status: "completed", elapsedMs: 7200 }, { id: "reviewing", label: "Reviewing patch", status: "completed", elapsedMs: 11300 }],
  activity: [
    { id: "1", stage: "understanding", action: "Parsed issue requirements", detail: "Loaded issue #123 and its description.", elapsedMs: 400, status: "completed" },
    { id: "2", stage: "understanding", action: "Read discussion", detail: "No issue comments were present.", elapsedMs: 1200, status: "completed" },
    { id: "3", stage: "exploring", action: "Scanned repository tree", detail: "Scanned repository tree: 184 candidate source files on main.", elapsedMs: 2300, status: "completed" },
    { id: "4", stage: "exploring", action: "Search: theme persistence refresh", detail: "3 likely matches found.", elapsedMs: 2800, status: "completed" },
    { id: "5", stage: "exploring", action: "Read src/hooks/useTheme.ts", detail: "Theme state initializes with a hard-coded default.", elapsedMs: 3300, status: "completed" },
    { id: "6", stage: "exploring", action: "Read src/providers/ThemeProvider.tsx", detail: "Theme applies but never persists the selection.", elapsedMs: 3800, status: "completed" },
    { id: "7", stage: "planning", action: "Created implementation plan", detail: "4 focused steps generated.", elapsedMs: 4700, status: "completed" },
    { id: "8", stage: "writing", action: "Modified src/hooks/useTheme.ts", detail: "Proposed edit (+14 −3).", elapsedMs: 6400, status: "completed" },
    { id: "9", stage: "writing", action: "Generated unified diff", detail: "Built a reviewable patch from 2 inspected source files.", elapsedMs: 7200, status: "completed" },
    { id: "10", stage: "reviewing", action: "Issue requirements covered", detail: "Reviewer check passed.", elapsedMs: 9000, status: "completed" },
    { id: "11", stage: "reviewing", action: "Existing API preserved", detail: "Reviewer check passed.", elapsedMs: 9700, status: "completed" },
    { id: "12", stage: "reviewing", action: "Tests not executed", detail: "Manual follow-up is recommended.", elapsedMs: 11300, status: "warning" },
  ],
  searches: [{ query: "theme persistence refresh", matches: 3, detail: "Ranked relevant state and provider files." }],
  inspectedFiles: [{ path: "src/hooks/useTheme.ts", reason: "Issue terms matched this path: theme.", finding: "Theme state initializes with a hard-coded default.", lines: 42 }, { path: "src/providers/ThemeProvider.tsx", reason: "This provider applies the theme state.", finding: "The selected value is never persisted.", lines: 57 }, { path: "src/app/layout.tsx", reason: "Checked for conflicting initialization.", finding: "No conflicting theme initialization found.", lines: 31 }],
  plan: [{ id: "1", title: "Locate theme initialization", detail: "src/hooks/useTheme.ts", status: "completed" }, { id: "2", title: "Add persistence mechanism", detail: "Store selection through the existing hook setter.", status: "completed" }, { id: "3", title: "Restore persisted preference", detail: "Apply the restored theme after browser hydration.", status: "completed" }, { id: "4", title: "Preserve external API", detail: "No calling-code changes required.", status: "completed" }],
  files: [{ path: "src/hooks/useTheme.ts", additions: 14, deletions: 3, reason: "Initializes from browser storage and writes changes back to storage.", diff: "@@ -4,10 +4,21 @@\n export function useTheme() {\n-  const [theme, setTheme] = useState<Theme>(\"light\");\n+  const [theme, setTheme] = useState<Theme>(() => {\n+    if (typeof window === \"undefined\") return \"light\";\n+    return (localStorage.getItem(\"theme\") as Theme) ?? \"light\";\n+  });\n \n-  return { theme, setTheme };\n+  const updateTheme = (nextTheme: Theme) => {\n+    setTheme(nextTheme);\n+    localStorage.setItem(\"theme\", nextTheme);\n+  };\n+\n+  return { theme, setTheme: updateTheme };\n }" }, { path: "src/providers/ThemeProvider.tsx", additions: 7, deletions: 1, reason: "Applies the restored value after hydration.", diff: "@@ -12,7 +12,13 @@\n-  useEffect(() => document.documentElement.dataset.theme = theme, [theme]);\n+  useEffect(() => {\n+    document.documentElement.dataset.theme = theme;\n+    document.documentElement.style.colorScheme = theme;\n+  }, [theme]);" }],
  explanations: [{ path: "src/hooks/useTheme.ts", explanation: "Stores the selected theme and initializes state from the saved browser value.", coverage: ["Theme survives refresh", "Server rendering stays safe"] }, { path: "src/providers/ThemeProvider.tsx", explanation: "Ensures the restored preference is applied when the provider initializes.", coverage: ["Existing provider API unchanged"] }],
  review: { status: "passed", checks: [{ label: "Issue requirements covered", status: "passed" }, { label: "Existing interfaces preserved", status: "passed" }, { label: "No unrelated modifications", status: "passed" }, { label: "Tests were not executed", status: "warning" }] },
  confidence: "high", limitations: ["Repository code was not executed.", "Automated tests were not run."],
  metrics: { elapsedMs: 11300, filesIndexed: 184, filesInspected: 3, searches: 1, filesChanged: 2, additions: 21, deletions: 4 },
  patch: "diff --git a/src/hooks/useTheme.ts b/src/hooks/useTheme.ts\n--- a/src/hooks/useTheme.ts\n+++ b/src/hooks/useTheme.ts\n@@ -4,10 +4,21 @@\n-  const [theme, setTheme] = useState<Theme>(\"light\");\n+  const [theme, setTheme] = useState<Theme>(() => {\n+    if (typeof window === \"undefined\") return \"light\";\n+    return (localStorage.getItem(\"theme\") as Theme) ?? \"light\";\n+  });\n",
};

function Icon({ name }: { name: string }) {
  const paths: Record<string, string> = { arrow: "M5 12h14m-6-6 6 6-6 6", play: "m8 5 11 7-11 7V5Z", download: "M12 3v12m0 0 4-4m-4 4-4m-5 8h18", check: "m5 12 4 4L19 6", file: "M14 2H6a2 2 0 0 0 2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8Z M14 2v6h6", copy: "M8 8h11v11H8z M5 16H4a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1h10a1 1 0 0 1 1 1v1", external: "M14 5h5v5m0-5-8 8 M19 14v5H5V5h5", close: "m6 6 12 12M18 6 6 18" };
  return <svg className="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" aria-hidden="true"><path d={paths[name]} strokeLinecap="round" strokeLinejoin="round" /></svg>;
}

function formatTime(ms: number) { return (ms / 1000).toFixed(1) + "s"; }
function liveShell(issue: PilotRun["issue"], repository: PilotRun["repository"]): Partial<PilotRun> {
  return { issue, repository, source: "live", status: "needs-review", summary: "", stages: sample.stages.map((stage, index) => ({ ...stage, status: index === 0 ? "investigating" : "pending", elapsedMs: undefined })), activity: [], searches: [], inspectedFiles: [], plan: [], files: [], explanations: [], review: { status: "warning", checks: [] }, confidence: "low", limitations: [], metrics: { elapsedMs: 0, filesIndexed: 0, filesInspected: 0, searches: 0, filesChanged: 0, additions: 0, deletions: 0 }, patch: "" };
}

export default function Home() {
  const [url, setUrl] = useState("");
  const [run, setRun] = useState<Partial<PilotRun> | null>(null);
  const [tab, setTab] = useState<"plan" | "diff" | "explanation">("diff");
  const [fileIndex, setFileIndex] = useState(0);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<RunError | null>(null);
  const [expanded, setExpanded] = useState<string | null>(null);
  const [how, setHow] = useState(false);
  const active = (run || sample) as PilotRun;
  const activeStage = active.stages.find((stage) => stage.status === "investigating");

  useEffect(() => {
    document.title = loading ? "Codex Pilot · Investigating " + (active.issue?.repository || "issue") : active.source === "live" && active.files.length ? "Codex Pilot · Patch ready" : "Codex Pilot — Autonomous GitHub Issue Solver";
  }, [loading, active.issue?.repository, active.source, active.files.length]);

  function receive(event: RunEvent) {
    if (event.type === "context") { setRun(liveShell(event.issue, event.repository)); return; }
    if (event.type === "completed") { setRun(event.run); setFileIndex(0); setTab("diff"); setLoading(false); return; }
    if (event.type === "failed") { setError(event.error); setLoading(false); return; }
    setRun((previous) => {
      if (!previous) return previous;
      if (event.type === "stage") return { ...previous, stages: (previous.stages || []).map((stage) => stage.id === event.stage.id ? event.stage : stage) };
      if (event.type === "activity") return { ...previous, activity: [...(previous.activity || []), event.activity] };
      if (event.type === "search") return { ...previous, searches: [...(previous.searches || []), event.search] };
      if (event.type === "inspection") return { ...previous, inspectedFiles: [...(previous.inspectedFiles || []), event.inspection] };
      if (event.type === "plan") return { ...previous, plan: event.plan };
      return previous;
    });
  }

  async function start(event: FormEvent, supplied?: string) {
    event.preventDefault();
    const issueUrl = supplied || url;
    setError(null); setFileIndex(0);
    if (!issueUrl.trim()) { setRun(null); setTab("diff"); return; }
    if (hostedPreview) {
      setError({ code: "hosted_preview", title: "Live runs are available in the local demo", message: "This hosted preview intentionally shows a sample run. Start Codex Pilot on the Codex-authenticated demo machine to investigate a public GitHub issue." });
      return;
    }
    setRun(null); setLoading(true);
    try {
      const response = await fetch("/api/runs", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ issueUrl }) });
      if (!response.ok || !response.body) { const data = await response.json().catch(() => ({})); throw new Error(data.error || "Could not start Codex Pilot."); }
      const reader = response.body.getReader(); const decoder = new TextDecoder(); let buffer = "";
      for (;;) {
        const part = await reader.read();
        buffer += decoder.decode(part.value || new Uint8Array(), { stream: !part.done });
        const messages = buffer.split("\n\n"); buffer = messages.pop() || "";
        messages.forEach((message) => { const data = message.split("\n").find((line) => line.startsWith("data: ")); if (data) receive(JSON.parse(data.slice(6)) as RunEvent); });
        if (part.done) break;
      }
    } catch (caught) {
      setError({ code: "network_error", title: "Could not start Codex Pilot", message: caught instanceof Error ? caught.message : "Check your connection and try again.", retryable: true });
      setLoading(false);
    }
  }
  function download() { const blob = new Blob([active.patch], { type: "text/x-diff" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = "issue-" + active.issue.number + "-fix.patch"; link.click(); URL.revokeObjectURL(link.href); }
  function copy() { void navigator.clipboard.writeText(active.patch); }
  const stageActivity = (id: string) => active.activity.filter((item) => item.stage === id);

  return <main className="min-h-screen bg-[#090b10] text-slate-100 selection:bg-cyan-400/30">
    <header className="border-b border-white/[.08] px-5 py-4 lg:px-8"><div className="mx-auto flex max-w-[1500px] items-center justify-between"><Link className="flex items-center gap-3" href="/"><span className="grid h-9 w-9 place-items-center rounded-xl bg-gradient-to-br from-cyan-300 to-blue-600 text-[#07131c]"><Icon name="arrow" /></span><span className="font-semibold tracking-tight">Codex <span className="text-cyan-300">Pilot</span></span></Link><div className="hidden items-center gap-3 text-xs text-slate-500 sm:flex"><span className={(loading ? "animate-pulse bg-cyan-300" : "bg-emerald-400") + " h-2 w-2 rounded-full shadow-[0_0_12px_currentColor]"} />{loading ? (activeStage?.label || "Starting investigation") : "Agentic coding, visible."}</div></div></header>
    <section className="border-b border-white/[.08] bg-[radial-gradient(ellipse_at_top,#11233a_0%,transparent_55%)] px-5 py-10 lg:px-8"><div className="mx-auto max-w-[1120px]"><p className="mb-3 text-xs font-medium tracking-[.18em] text-cyan-300">AUTONOMOUS REPOSITORY INVESTIGATION</p><h1 className="max-w-2xl text-3xl font-semibold tracking-tight text-white sm:text-5xl">Paste the issue. Watch Codex find the fix.</h1><p className="mt-4 max-w-xl text-sm leading-6 text-slate-400 sm:text-base">Codex Pilot explores an unfamiliar public repository selectively, proposes a patch, and shows the evidence behind it.</p>
      <form onSubmit={(event) => start(event)} className="mt-7 flex flex-col gap-3 sm:flex-row"><div className="flex flex-1 items-center gap-3 rounded-xl border border-white/10 bg-black/30 px-4 focus-within:border-cyan-300/60"><span className="text-slate-600">github.com/</span><input value={url} onChange={(event) => setUrl(event.target.value)} className="h-12 min-w-0 flex-1 bg-transparent text-sm text-white outline-none placeholder:text-slate-600" placeholder="owner/repo/issues/123" aria-label="GitHub issue URL" /></div><button disabled={loading || hostedPreview} className="flex h-12 items-center justify-center gap-2 rounded-xl bg-cyan-300 px-5 text-sm font-semibold text-[#07131c] transition hover:bg-cyan-200 disabled:cursor-wait disabled:opacity-70"><Icon name="play" />{loading ? "Investigating…" : hostedPreview ? "Live runs on local demo" : "Run Codex Pilot"}</button></form>
      <p className="mt-3 text-xs text-slate-500">Works with public GitHub issues · No repository execution · Generates patch only</p>
      {hostedPreview && <div className="mt-4 rounded-xl border border-amber-300/25 bg-amber-300/[.06] px-4 py-3 text-xs leading-5 text-amber-100"><p className="font-medium tracking-[.12em] text-amber-200">HOSTED PREVIEW</p><p className="mt-1 text-amber-100/75">Sample run only. Live public-issue investigation is available on the local Codex-authenticated demo machine.</p></div>}
      <div className="mt-5 flex flex-wrap items-center gap-2"><span className="mr-1 text-xs text-slate-500">Try an example</span>{examples.map((example) => <button key={example.url} onClick={(event) => { setUrl(example.url); void start(event as unknown as FormEvent, example.url); }} disabled={loading || hostedPreview} className="rounded-full border border-white/10 bg-white/[.03] px-3 py-1.5 font-mono text-[11px] text-slate-300 hover:border-cyan-300/40 hover:text-cyan-200 disabled:opacity-50">{example.label}</button>)}<button onClick={() => { setRun(null); setError(null); setTab("diff"); }} className="rounded-full border border-amber-300/20 bg-amber-300/[.04] px-3 py-1.5 text-[11px] text-amber-100/80">View sample run</button></div></div></section>
    <section className="mx-auto max-w-[1500px] px-5 py-7 lg:px-8">
      {error && <div role="alert" className="mb-6 rounded-2xl border border-rose-300/20 bg-rose-300/[.05] p-5"><p className="font-medium text-rose-100">{error.title}</p><p className="mt-1 text-sm leading-6 text-rose-100/70">{error.message}</p>{error.retryable && <button onClick={(event) => start(event as unknown as FormEvent)} className="mt-3 text-xs font-medium text-cyan-200">Try again →</button>}</div>}
      <div className="mb-6 flex flex-col justify-between gap-4 rounded-2xl border border-white/[.08] bg-[#0d1118] p-5 sm:flex-row sm:items-center"><div className="min-w-0"><div className="flex items-center gap-2"><p className="font-mono text-xs text-cyan-200">{active.issue.repository}</p><span className={(active.source === "live" ? "border-cyan-300/30 bg-cyan-300/10 text-cyan-200" : "border-amber-300/30 bg-amber-300/10 text-amber-200") + " rounded-full border px-2 py-0.5 text-[10px] font-medium tracking-[.12em]"}>{active.source === "live" ? "LIVE RUN" : "SAMPLE RUN"}</span></div><h2 className="mt-2 truncate text-lg font-medium text-white">Issue #{active.issue.number} · {active.issue.title}</h2><div className="mt-3 flex flex-wrap gap-x-4 gap-y-1 text-xs text-slate-500"><span>Branch: <b className="font-medium text-slate-300">{active.repository.branch}</b></span><span>Language: <b className="font-medium text-slate-300">{active.repository.language}</b></span><span>Public repository</span><a className="inline-flex items-center gap-1 text-cyan-300" href={active.issue.url} target="_blank" rel="noreferrer">View on GitHub <Icon name="external" /></a></div></div>{active.patch && <div className="flex gap-2"><button onClick={copy} className="inline-flex items-center gap-2 rounded-lg border border-white/10 px-3 py-2 text-xs text-slate-200"><Icon name="copy" />Copy</button><button onClick={download} className="inline-flex items-center gap-2 rounded-lg bg-cyan-300 px-3 py-2 text-xs font-semibold text-[#07131c]"><Icon name="download" />Download .diff</button></div>}</div>
      {active.files.length > 0 && <section className="mb-5 rounded-2xl border border-cyan-300/20 bg-cyan-300/[.045] p-5"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="text-[10px] font-medium tracking-[.16em] text-cyan-300">PATCH READY</p><p className="mt-1 text-lg font-medium text-white">{active.metrics.filesChanged || active.files.length} files changed <span className="font-mono text-sm text-emerald-300">+{active.metrics.additions}</span> <span className="font-mono text-sm text-rose-300">−{active.metrics.deletions}</span></p></div><div className="flex gap-2"><button onClick={() => setTab("diff")} className="rounded-lg border border-cyan-300/25 px-3 py-2 text-xs font-medium text-cyan-100">View Diff</button><button onClick={download} className="inline-flex items-center gap-2 rounded-lg bg-cyan-300 px-3 py-2 text-xs font-semibold text-[#07131c]"><Icon name="download" />Download Patch</button></div></div><div className="mt-5 grid gap-3 border-t border-cyan-300/10 pt-4 sm:grid-cols-5"><Metric value={formatTime(active.metrics.elapsedMs)} label="Solved in" /><Metric value={String(active.metrics.filesIndexed)} label="Candidate files scanned" /><Metric value={String(active.metrics.filesInspected || active.inspectedFiles.length)} label="Files inspected" /><Metric value={String(active.metrics.searches || active.searches.length)} label="Searches made" /><Metric value={String(active.metrics.filesChanged || active.files.length)} label="Files changed" /></div></section>}
      <div className="grid gap-5 lg:grid-cols-[.9fr_1.4fr]"><aside className="rounded-2xl border border-white/[.08] bg-[#0d1118] p-5 shadow-2xl shadow-black/20"><div className="mb-5 flex justify-between"><h3 className="text-sm font-medium">Agent Activity</h3><span className="font-mono text-xs text-slate-500">{loading ? "live" : formatTime(active.metrics.elapsedMs)}</span></div>
        <div className="space-y-5">{active.stages.map((stage) => <div key={stage.id}><div className="mb-2 flex justify-between"><p className={(stage.status === "investigating" ? "text-cyan-300" : "text-slate-600") + " text-[10px] font-medium tracking-[.14em]"}>{stage.label.toUpperCase()}</p>{stage.elapsedMs && <span className="font-mono text-[10px] text-slate-600">{formatTime(stage.elapsedMs)}</span>}</div><div className="space-y-3">{stageActivity(stage.id).map((item) => <ActivityRow item={item} key={item.id} />)}{stage.status === "investigating" && <div className="flex gap-3"><span className="mt-1 h-3.5 w-3.5 animate-spin rounded-full border-2 border-cyan-300/30 border-t-cyan-300" /><p className="text-xs text-cyan-100">Investigating…</p></div>}{stage.status === "pending" && !stageActivity(stage.id).length && <p className="pl-6 text-[11px] text-slate-700">Pending</p>}</div></div>)}</div>
        <div className="mt-6 border-t border-white/[.07] pt-5"><p className="mb-3 text-[10px] font-medium tracking-[.14em] text-slate-600">SEARCHES PERFORMED</p>{active.searches.map((search) => <div className="mb-2 rounded-lg bg-black/20 px-3 py-2 font-mono text-[11px] text-slate-400" key={search.query}>Search: <span className="text-cyan-200">{search.query}</span><br /><span className="text-slate-600">→ {search.matches || "relevant"} matches</span></div>)}</div>
        <div className="mt-6 border-t border-white/[.07] pt-5"><p className="mb-3 text-[10px] font-medium tracking-[.14em] text-slate-600">FILES INSPECTED</p>{active.inspectedFiles.map((item) => <InspectionRow item={item} expanded={expanded === item.path} toggle={() => setExpanded(expanded === item.path ? null : item.path)} key={item.path} />)}</div>
      </aside><section className="overflow-hidden rounded-2xl border border-white/[.08] bg-[#0d1118] shadow-2xl shadow-black/20"><div className="flex gap-1 border-b border-white/[.08] p-2">{(["plan", "diff", "explanation"] as const).map((name) => <button key={name} onClick={() => setTab(name)} className={(tab === name ? "bg-white/[.09] text-white" : "text-slate-500") + " rounded-lg px-3 py-2 text-xs capitalize"}>{name}{name === "diff" && <span className="ml-1.5 text-cyan-300">{active.files.length}</span>}</button>)}</div>
        {tab === "plan" && <Plan run={active} />}{tab === "diff" && <Diff run={active} index={fileIndex} setIndex={setFileIndex} />}{tab === "explanation" && <Explain run={active} />}</section></div>
      <button onClick={() => setHow(true)} className="mt-5 inline-flex items-center gap-2 text-xs text-slate-500 hover:text-cyan-200">How Codex solved this <Icon name="arrow" /></button>
    </section>{how && <How close={() => setHow(false)} />}</main>;
}

function ActivityRow({ item }: { item: Activity }) { return <div className="flex gap-3"><span className={(item.status === "warning" ? "bg-amber-300/15 text-amber-200" : "bg-emerald-400/15 text-emerald-300") + " mt-0.5 grid h-4 w-4 shrink-0 place-items-center rounded-full"}><Icon name="check" /></span><div><p className="text-xs text-slate-200">{item.action}</p><p className="mt-0.5 text-[11px] leading-4 text-slate-500">{item.detail}</p></div></div>; }
function InspectionRow({ item, expanded, toggle }: { item: InspectedFile; expanded: boolean; toggle: () => void }) { return <div className="rounded-lg hover:bg-white/[.035]"><button onClick={toggle} className="flex w-full items-center gap-2 px-2 py-1.5 text-left font-mono text-[11px] text-slate-400"><span className="text-cyan-300"><Icon name="file" /></span><span className="min-w-0 flex-1 truncate">{item.path}</span><span>{expanded ? "−" : "+"}</span></button>{expanded && <div className="mx-2 mb-2 rounded-md border border-cyan-300/10 bg-cyan-300/[.035] p-3"><p className="text-[10px] font-medium tracking-[.12em] text-cyan-300">WHY CODEX OPENED THIS</p><p className="mt-1 text-[11px] leading-4 text-slate-400">{item.reason}</p><p className="mt-2 text-[11px] leading-4 text-slate-500">→ {item.finding}</p></div>}</div>; }
function Plan({ run }: { run: PilotRun }) { return <div className="p-6"><p className="text-[10px] font-medium tracking-[.16em] text-cyan-300">IMPLEMENTATION PLAN</p><div className="mt-4 rounded-xl border border-cyan-300/10 bg-cyan-300/[.035] p-4 text-sm leading-6 text-slate-300">{run.summary || "Codex Pilot is assembling evidence."}</div><div className="mt-6 space-y-4">{run.plan.map((step, index) => <div className="flex gap-4" key={step.id}><span className="grid h-6 w-6 shrink-0 place-items-center rounded-full border border-emerald-300/30 bg-emerald-300/10 font-mono text-xs text-emerald-200">✓</span><div><p className="text-sm text-slate-200"><span className="mr-2 font-mono text-cyan-200">{String(index + 1).padStart(2, "0")}</span>{step.title}</p><p className="mt-0.5 text-xs text-slate-500">{step.detail}</p></div></div>)}</div></div>; }
function Diff({ run, index, setIndex }: { run: PilotRun; index: number; setIndex: (n: number) => void }) { const file = run.files[index]; if (!file) return <div className="grid min-h-[420px] place-items-center p-8 text-center"><div><p className="text-sm text-slate-300">Patch workspace</p><p className="mt-2 text-xs leading-5 text-slate-600">The generated diff becomes the hero result when Codex has enough evidence.</p></div></div>; return <div><div className="flex flex-wrap gap-1 border-b border-white/[.08] px-3 py-2">{run.files.map((change, i) => <button onClick={() => setIndex(i)} className={(index === i ? "bg-cyan-300/10 text-cyan-200" : "text-slate-500") + " rounded-md px-2 py-1 font-mono text-[11px]"} key={change.path}>{change.path.split("/").pop()} <span className="text-emerald-400">+{change.additions}</span> <span className="text-rose-400">−{change.deletions}</span></button>)}</div><div className="p-5"><div className="mb-4 flex justify-between gap-3"><div><p className="font-mono text-xs text-cyan-100">{file.path}</p><p className="mt-1 text-xs text-slate-500">{file.reason}</p></div><span className="h-fit rounded-full border border-emerald-300/20 bg-emerald-300/[.06] px-2 py-1 text-[10px] text-emerald-200">PATCH READY</span></div><pre className="max-h-[480px] overflow-auto rounded-xl border border-white/[.07] bg-[#080a0e] p-4 font-mono text-xs leading-5 text-slate-300">{file.diff.split("\n").map((line, i) => <span className={line.startsWith("+") ? "block bg-emerald-400/[.08] text-emerald-200" : line.startsWith("-") ? "block bg-rose-400/[.08] text-rose-200" : line.startsWith("@@") ? "block text-cyan-300" : "block"} key={i}>{line || " "}</span>)}</pre></div></div>; }
function Explain({ run }: { run: PilotRun }) { return <div className="p-6"><h3 className="text-base font-medium text-white">Why these changes?</h3><div className="mt-5 space-y-5">{run.explanations.map((item) => <div className="border-l-2 border-cyan-300/30 pl-4" key={item.path}><p className="font-mono text-xs text-cyan-200">{item.path}</p><p className="mt-2 text-sm leading-6 text-slate-300">{item.explanation}</p>{item.coverage.map((coverage) => <span className="mr-2 mt-2 inline-block rounded-full bg-emerald-400/10 px-2 py-1 text-[10px] text-emerald-200" key={coverage}>✓ {coverage}</span>)}</div>)}</div><div className="mt-8 grid gap-3 sm:grid-cols-2"><div className="rounded-xl border border-cyan-300/10 bg-cyan-300/[.035] p-4"><p className="text-[10px] font-medium tracking-[.14em] text-cyan-300">PATCH REVIEW</p>{run.review.checks.map((check) => <p className={(check.status === "passed" ? "text-emerald-200" : "text-amber-100") + " mt-2 text-xs"} key={check.label}>{check.status === "passed" ? "✓" : "⚠"} {check.label}</p>)}</div><div className="rounded-xl border border-amber-300/10 bg-amber-300/[.035] p-4"><p className="text-[10px] font-medium tracking-[.14em] text-amber-200">NOT VERIFIED</p>{run.limitations.map((item) => <p className="mt-2 text-xs text-amber-100/70" key={item}>⚠ {item}</p>)}</div></div></div>; }
function Metric({ value, label }: { value: string; label: string }) { return <div><p className="font-mono text-xl text-white">{value}</p><p className="mt-1 text-[10px] font-medium tracking-[.14em] text-slate-500">{label.toUpperCase()}</p></div>; }
function How({ close }: { close: () => void }) { const steps = ["GitHub Issue", "Investigator", "Repository Explorer", "Planner", "Coder", "Reviewer", "Patch"]; return <div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-5" role="dialog" aria-modal="true"><div className="w-full max-w-lg rounded-2xl border border-white/10 bg-[#0d1118] p-6 shadow-2xl"><div className="flex justify-between"><div><p className="text-[10px] font-medium tracking-[.16em] text-cyan-300">HOW IT WORKS</p><h3 className="mt-2 text-lg font-medium text-white">Agentic coding, visible.</h3></div><button onClick={close} className="text-slate-500" aria-label="Close"><Icon name="close" /></button></div><div className="mt-6 space-y-2">{steps.map((step, index) => <div className="flex items-center gap-3" key={step}><span className="grid h-7 w-7 place-items-center rounded-full border border-cyan-300/20 bg-cyan-300/[.05] font-mono text-xs text-cyan-200">{index + 1}</span><p className="text-sm text-slate-300">{step}</p></div>)}</div><p className="mt-6 border-t border-white/[.07] pt-4 text-xs leading-5 text-slate-500">Codex Pilot never clones, executes, tests, or modifies the target repository. It exposes the evidence used to propose a reviewable patch.</p></div></div>; }
